export interface CountryOption {
  code: string
  name: string
}

export const COUNTRIES: CountryOption[] = [
  { code: 'US', name: 'United States (US)' },
  { code: 'GB', name: 'United Kingdom (GB)' },
  { code: 'CA', name: 'Canada (CA)' },
  { code: 'NG', name: 'Nigeria (NG)' },
  { code: 'DE', name: 'Germany (DE)' },
  { code: 'FR', name: 'France (FR)' },
  { code: 'JP', name: 'Japan (JP)' },
  { code: 'CN', name: 'China (CN)' },
  { code: 'IN', name: 'India (IN)' },
  { code: 'AU', name: 'Australia (AU)' },
  { code: 'BR', name: 'Brazil (BR)' },
  { code: 'ZA', name: 'South Africa (ZA)' },
  { code: 'AE', name: 'United Arab Emirates (AE)' },
  { code: 'SG', name: 'Singapore (SG)' },
  { code: 'SA', name: 'Saudi Arabia (SA)' },
  { code: 'GH', name: 'Ghana (GH)' },
  { code: 'KE', name: 'Kenya (KE)' },
  { code: 'MX', name: 'Mexico (MX)' },
  { code: 'IT', name: 'Italy (IT)' },
  { code: 'ES', name: 'Spain (ES)' },
  { code: 'NL', name: 'Netherlands (NL)' },
  { code: 'SE', name: 'Sweden (SE)' },
  { code: 'CH', name: 'Switzerland (CH)' },
  { code: 'KR', name: 'South Korea (KR)' },
  { code: 'EG', name: 'Egypt (EG)' },
  { code: 'CO', name: 'Colombia (CO)' },
  { code: 'AR', name: 'Argentina (AR)' },
  { code: 'TR', name: 'Turkey (TR)' },
  { code: 'TH', name: 'Thailand (TH)' },
  { code: 'ID', name: 'Indonesia (ID)' },
  { code: 'MY', name: 'Malaysia (MY)' },
  { code: 'PH', name: 'Philippines (PH)' },
  { code: 'PK', name: 'Pakistan (PK)' },
  { code: 'VN', name: 'Vietnam (VN)' },
  { code: 'PL', name: 'Poland (PL)' },
  { code: 'BE', name: 'Belgium (BE)' },
  { code: 'AT', name: 'Austria (AT)' },
  { code: 'NZ', name: 'New Zealand (NZ)' },
  { code: 'IE', name: 'Ireland (IE)' },
  { code: 'DK', name: 'Denmark (DK)' },
  { code: 'FI', name: 'Finland (FI)' },
  { code: 'NO', name: 'Norway (NO)' },
  { code: 'CZ', name: 'Czechia (CZ)' },
  { code: 'PT', name: 'Portugal (PT)' },
  { code: 'CL', name: 'Chile (CL)' },
  { code: 'PE', name: 'Peru (PE)' },
  { code: 'AF', name: 'Afghanistan (AF)' },
  { code: 'AL', name: 'Albania (AL)' },
  { code: 'DZ', name: 'Algeria (DZ)' },
  { code: 'AD', name: 'Andorra (AD)' },
  { code: 'AO', name: 'Angola (AO)' },
  { code: 'AG', name: 'Antigua and Barbuda (AG)' },
  { code: 'AM', name: 'Armenia (AM)' },
  { code: 'AW', name: 'Aruba (AW)' },
  { code: 'AZ', name: 'Azerbaijan (AZ)' },
  { code: 'BS', name: 'Bahamas (BS)' },
  { code: 'BH', name: 'Bahrain (BH)' },
  { code: 'BD', name: 'Bangladesh (BD)' },
  { code: 'BB', name: 'Barbados (BB)' },
  { code: 'BY', name: 'Belarus (BY)' },
  { code: 'BZ', name: 'Belize (BZ)' },
  { code: 'BJ', name: 'Benin (BJ)' },
  { code: 'BM', name: 'Bermuda (BM)' },
  { code: 'BT', name: 'Bhutan (BT)' },
  { code: 'BO', name: 'Bolivia (BO)' },
  { code: 'BA', name: 'Bosnia and Herzegovina (BA)' },
  { code: 'BW', name: 'Botswana (BW)' },
  { code: 'BN', name: 'Brunei (BN)' },
  { code: 'BG', name: 'Bulgaria (BG)' },
  { code: 'BF', name: 'Burkina Faso (BF)' },
  { code: 'BI', name: 'Burundi (BI)' },
  { code: 'KH', name: 'Cambodia (KH)' },
  { code: 'CM', name: 'Cameroon (CM)' },
  { code: 'CV', name: 'Cape Verde (CV)' },
  { code: 'KY', name: 'Cayman Islands (KY)' },
  { code: 'CF', name: 'Central African Republic (CF)' },
  { code: 'TD', name: 'Chad (TD)' },
  { code: 'KM', name: 'Comoros (KM)' },
  { code: 'CG', name: 'Congo (CG)' },
  { code: 'CD', name: 'Congo, Democratic Republic (CD)' },
  { code: 'CR', name: 'Costa Rica (CR)' },
  { code: 'HR', name: 'Croatia (HR)' },
  { code: 'CU', name: 'Cuba (CU)' },
  { code: 'CY', name: 'Cyprus (CY)' },
  { code: 'DJ', name: 'Djibouti (DJ)' },
  { code: 'DM', name: 'Dominica (DM)' },
  { code: 'DO', name: 'Dominican Republic (DO)' },
  { code: 'EC', name: 'Ecuador (EC)' },
  { code: 'SV', name: 'El Salvador (SV)' },
  { code: 'GQ', name: 'Equatorial Guinea (GQ)' },
  { code: 'ER', name: 'Eritrea (ER)' },
  { code: 'EE', name: 'Estonia (EE)' },
  { code: 'SZ', name: 'Eswatini (SZ)' },
  { code: 'ET', name: 'Ethiopia (ET)' },
  { code: 'FJ', name: 'Fiji (FJ)' },
  { code: 'GA', name: 'Gabon (GA)' },
  { code: 'GM', name: 'Gambia (GM)' },
  { code: 'GE', name: 'Georgia (GE)' },
  { code: 'GR', name: 'Greece (GR)' },
  { code: 'GD', name: 'Grenada (GD)' },
  { code: 'GT', name: 'Guatemala (GT)' },
  { code: 'GN', name: 'Guinea (GN)' },
  { code: 'GW', name: 'Guinea-Bissau (GW)' },
  { code: 'GY', name: 'Guyana (GY)' },
  { code: 'HT', name: 'Haiti (HT)' },
  { code: 'HN', name: 'Honduras (HN)' },
  { code: 'HK', name: 'Hong Kong (HK)' },
  { code: 'HU', name: 'Hungary (HU)' },
  { code: 'IS', name: 'Iceland (IS)' },
  { code: 'IR', name: 'Iran (IR)' },
  { code: 'IQ', name: 'Iraq (IQ)' },
  { code: 'IL', name: 'Israel (IL)' },
  { code: 'JM', name: 'Jamaica (JM)' },
  { code: 'JO', name: 'Jordan (JO)' },
  { code: 'KZ', name: 'Kazakhstan (KZ)' },
  { code: 'KW', name: 'Kuwait (KW)' },
  { code: 'KG', name: 'Kyrgyzstan (KG)' },
  { code: 'LA', name: 'Laos (LA)' },
  { code: 'LV', name: 'Latvia (LV)' },
  { code: 'LB', name: 'Lebanon (LB)' },
  { code: 'LS', name: 'Lesotho (LS)' },
  { code: 'LR', name: 'Liberia (LR)' },
  { code: 'LY', name: 'Libya (LY)' },
  { code: 'LI', name: 'Liechtenstein (LI)' },
  { code: 'LT', name: 'Lithuania (LT)' },
  { code: 'LU', name: 'Luxembourg (LU)' },
  { code: 'MO', name: 'Macao (MO)' },
  { code: 'MG', name: 'Madagascar (MG)' },
  { code: 'MW', name: 'Malawi (MW)' },
  { code: 'MV', name: 'Maldives (MV)' },
  { code: 'ML', name: 'Mali (ML)' },
  { code: 'MT', name: 'Malta (MT)' },
  { code: 'MR', name: 'Mauritania (MR)' },
  { code: 'MU', name: 'Mauritius (MU)' },
  { code: 'MD', name: 'Moldova (MD)' },
  { code: 'MC', name: 'Monaco (MC)' },
  { code: 'MN', name: 'Mongolia (MN)' },
  { code: 'ME', name: 'Montenegro (ME)' },
  { code: 'MA', name: 'Morocco (MA)' },
  { code: 'MZ', name: 'Mozambique (MZ)' },
  { code: 'MM', name: 'Myanmar (MM)' },
  { code: 'NA', name: 'Namibia (NA)' },
  { code: 'NP', name: 'Nepal (NP)' },
  { code: 'NI', name: 'Nicaragua (NI)' },
  { code: 'NE', name: 'Niger (NE)' },
  { code: 'MK', name: 'North Macedonia (MK)' },
  { code: 'OM', name: 'Oman (OM)' },
  { code: 'PA', name: 'Panama (PA)' },
  { code: 'PG', name: 'Papua New Guinea (PG)' },
  { code: 'PY', name: 'Paraguay (PY)' },
  { code: 'QA', name: 'Qatar (QA)' },
  { code: 'RO', name: 'Romania (RO)' },
  { code: 'RU', name: 'Russia (RU)' },
  { code: 'RW', name: 'Rwanda (RW)' },
  { code: 'KN', name: 'Saint Kitts and Nevis (KN)' },
  { code: 'LC', name: 'Saint Lucia (LC)' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines (VC)' },
  { code: 'WS', name: 'Samoa (WS)' },
  { code: 'SM', name: 'San Marino (SM)' },
  { code: 'ST', name: 'Sao Tome and Principe (ST)' },
  { code: 'SN', name: 'Senegal (SN)' },
  { code: 'RS', name: 'Serbia (RS)' },
  { code: 'SC', name: 'Seychelles (SC)' },
  { code: 'SL', name: 'Sierra Leone (SL)' },
  { code: 'SK', name: 'Slovakia (SK)' },
  { code: 'SI', name: 'Slovenia (SI)' },
  { code: 'SB', name: 'Solomon Islands (SB)' },
  { code: 'SO', name: 'Somalia (SO)' },
  { code: 'SS', name: 'South Sudan (SS)' },
  { code: 'LK', name: 'Sri Lanka (LK)' },
  { code: 'SD', name: 'Sudan (SD)' },
  { code: 'SR', name: 'Suriname (SR)' },
  { code: 'SY', name: 'Syria (SY)' },
  { code: 'TW', name: 'Taiwan (TW)' },
  { code: 'TJ', name: 'Tajikistan (TJ)' },
  { code: 'TZ', name: 'Tanzania (TZ)' },
  { code: 'TL', name: 'Timor-Leste (TL)' },
  { code: 'TG', name: 'Togo (TG)' },
  { code: 'TO', name: 'Tonga (TO)' },
  { code: 'TT', name: 'Trinidad and Tobago (TT)' },
  { code: 'TN', name: 'Tunisia (TN)' },
  { code: 'TM', name: 'Turkmenistan (TM)' },
  { code: 'UG', name: 'Uganda (UG)' },
  { code: 'UA', name: 'Ukraine (UA)' },
  { code: 'UY', name: 'Uruguay (UY)' },
  { code: 'UZ', name: 'Uzbekistan (UZ)' },
  { code: 'VU', name: 'Vanuatu (VU)' },
  { code: 'VE', name: 'Venezuela (VE)' },
  { code: 'YE', name: 'Yemen (YE)' },
  { code: 'ZM', name: 'Zambia (ZM)' },
  { code: 'ZW', name: 'Zimbabwe (ZW)' }
]
